### ISSUE TITLE
Body margin-bottom VS body height 100%

### ISSUE THREAD

**Issue by dalibor983** [maximebf/php-debugbar#414]
What to do if I have css like this:
```css
html, body {
  height: 100%;
}
```

When debugbar adds margin-bottom to body, body goes out of view port for the same value as margin-bottom and I got vertical scroll bar.

**Comment by john-inkesta** [comment]
This is still an issue. I'm using FilamentPHP. Tags: Filament, TALL, Laravel

**Comment by nicolasbinet** [comment]
it would be nice to use `padding-bottom` instead of `margin-bottom`.

**Comment by BenceSzalai** [comment]
A more versatile solution would be to put classes to `<body>` to indicate the presence (and probably state, like `minimised` or `closed`) of the debug-bar as well to assigne a css variable e.g.: `--php-debugbar-height: 30px;` that would be updated in real-time to match the actual height. This way anyone with special layouts could easily put in place the rules they need in their CSS, e.g. for the case in this issue:
```css
body.has-phpdebugbar:not(.phpdebugbar-closed) {
   margin-bottom: 0 !important;
   padding-bottom: var(--php-debugbar-height);
}
```

Indeed with these classes and the CSS variables anyone could adjust the presentation to whatever complex-custom page structure they have in place.
