### ISSUE TITLE
Forcing display block to some css classes - to prevent mess with user defined css

### ISSUE THREAD

**Issue by simogeo** [maximebf/php-debugbar#509]
to prevent big mess with user defined css, you could add `display:block;` in css files.

For example here : https://github.com/maximebf/php-debugbar/blob/master/src/DebugBar/Resources/widgets.css#L142

```css
 dl.phpdebugbar-widgets-kvlist dd {
    margin-left: 160px;
    padding: 5px;
    border-top: 1px solid #eee;
    cursor: pointer;
    min-height: 17px;
    display:block;
  }
```
